project_id = "wunghdnjiqlkuotenoip"

[functions.vetorizar-sinapi]
enabled = true
verify_jwt = true
import_map = "./functions/vetorizar-sinapi/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/vetorizar-sinapi/index.ts"

[functions.calcular-quantitativos]
enabled = true
verify_jwt = true
import_map = "./functions/calcular-quantitativos/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/calcular-quantitativos/index.ts"

[functions.mercadopago-webhook]
verify_jwt = false
